spring.application.name: order-service

# Port
server.port: 8081

# CoffeeService
dev.sotoestevez.coffee:
    host: http://localhost:8080
    user: user
    password: password

# Log
logging.level:
    dev.sotoestevez: DEBUG
