[package]
name = "rhead"
description = "Clone of head command"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
common = { path = "../common" }

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true

