spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: inventory_service
    password: password

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform:  org.hibernate.dialect.MySQL8Dialect