# Port
server.port: 8082

# Database
spring.datasource:
  url: jdbc:h2:mem:inventory-service
  driver-class-name: org.h2.Driver
  username: sa

spring.sql.init.mode: embedded
spring.jpa.defer-datasource-initialization: true

# Log
logging.level:
  dev.sotoestevez: DEBUG

