micronaut:
  application:
    name: demo
  server:
    port: 8080
    cors:
      enabled: true
elasticsearch:
  httpHosts: http://localhost:9200
imdb:
  basics:
    key: imdb
    basePath: src/main/resources/imdb/
    file: title.basics.tsv
    indexConfig: _index_config.json
    bulk: 5000
    total: 7662622
  ratings:
    key: imdb
    basePath: src/main/resources/imdb/
    file: title.ratings.tsv
    indexConfig: _index_config.json
    bulk: 7500
    total: 1132578
reducedImdb:
  basics:
    key: test
    basePath: src/test/resources/test/
    file: test.basics.tsv
    indexConfig: index.json
    bulk: 5000
    total: 5000
  ratings:
    key: test
    basePath: src/test/resources/test/
    file: test.ratings.tsv
    indexConfig: index.json
    bulk: 5000
    total: 5000
