[workspace]
members = [
  "rcat",
  "recho",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = [ "Kriogenia <ricardo@sotoestevez.dev>"]

[workspace.dependencies]
assert_cmd = "2"
clap = { version = "4.4", features = [ "derive" ]}
predicates = "3"

