name: GoBank CI Tests

on:
  push:
    branches: [ go_bank ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go_bank

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: gobank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
        id: go

      - name: Install migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test

    
